### ISSUE TITLE
运行脚本提示AttributeError

### ISSUE THREAD

**Issue by ghost** [EricZhu-42/PedagogySquare_Downloader#3]
![image](https://user-images.githubusercontent.com/58081463/79074831-1fda1480-7d21-11ea-8052-e157d8d8dfcb.png)
Python版本3.8.2，系统Arch Linux。
可能是教学立方系统更新导致的？

**Comment by EricZhu-42** [comment]
谢谢你的反馈！

好像是的 前几天教学立方的更新可能修改了**页面结构或者XHR的格式** 这几天代码可能无法正常使用 我今晚开始修复这个问题

麻烦你关注repo首页的信息 修复该问题后我会在首页注明

再次感谢！

**Comment by EricZhu-42** [comment]
同学你好！

出现错误的原因是新版教学立方修改了**附件元数据的请求地址**与**附件元数据的XHR格式**。我已经更新了脚本，现在**应该可以正常使用了**。

但是，似乎新版教学立方推出了“课件文件夹”的功能。由于我还没有遇到老师使用该功能的例子，暂时无法适配，因此在处理**课件列表中的文件夹**时可能出错。我会在拿到数据之后修复这个功能，并发布新版本的release.

随时欢迎你的反馈！

**Comment by ghost** [comment]
thx :)

**Comment by ghost** [comment]
我恰好有一门课有课件中的文件夹，结果是出错了：
Traceback (most recent call last):
  File "download.py", line 137, in <module>
    with closing(requests.get(entry.get('path').replace('amp;', ''), stream=True)) as res:
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by EricZhu-42** [comment]
我刚刚在一个测试课程中确定了课件文件夹的相关请求地址——现在脚本会迭代地将各个文件夹中的所有文件（如有）加入全局的下载列表，最后统一进行下载，所以**脚本应该可以使用了**。

欢迎你Pull最新版本的代码进行测试。如果当前代码运行正常，我会发布新版本的release。

感谢你的关注！
